$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$RootDir = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $RootDir '.env.local'
$EnvMarker = '# Generated by TomeCMS local setup'

foreach ($CommandName in @('node', 'npm.cmd', 'docker', 'supabase')) {
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "Missing '$CommandName'. Install it and run this script again."
    }
}

& docker info *> $null
if ($LASTEXITCODE -ne 0) { throw 'Docker Desktop is not running.' }

$NodeMajor = [int](& node -p "process.versions.node.split('.')[0]")
if ($NodeMajor -lt 22) { throw 'Node.js 22 or newer is required.' }

Push-Location $RootDir
try {
    if (-not (Test-Path 'supabase/config.toml')) {
        & supabase init --yes
        if ($LASTEXITCODE -ne 0) { throw 'Supabase initialization failed.' }
    }

    & supabase start -x realtime,imgproxy,edge-runtime,logflare,vector,supavisor
    if ($LASTEXITCODE -ne 0) { throw 'Supabase failed to start.' }

    & supabase migration up --local
    if ($LASTEXITCODE -ne 0) { throw 'Local database migrations failed.' }

    $StatusLines = @(& supabase status -o env)
    if ($LASTEXITCODE -ne 0) { throw 'Could not read local Supabase credentials.' }

    function Get-StatusValue([string]$Name) {
        foreach ($Line in $StatusLines) {
            if ($Line -match "^$([regex]::Escape($Name))=(.*)$") {
                return $Matches[1].Trim('"')
            }
        }
        return ''
    }

    $ApiUrl = Get-StatusValue 'API_URL'
    $AnonKey = Get-StatusValue 'PUBLISHABLE_KEY'
    if (-not $AnonKey) { $AnonKey = Get-StatusValue 'ANON_KEY' }
    $ServiceRoleKey = Get-StatusValue 'SECRET_KEY'
    if (-not $ServiceRoleKey) { $ServiceRoleKey = Get-StatusValue 'SERVICE_ROLE_KEY' }
    $StudioUrl = Get-StatusValue 'STUDIO_URL'
    if (-not $ApiUrl -or -not $AnonKey -or -not $ServiceRoleKey) {
        throw 'Supabase did not return the required local credentials.'
    }

    $InstallToken = ''
    if (Test-Path $EnvFile) {
        $FirstLine = Get-Content $EnvFile -TotalCount 1
        if ($FirstLine -ne $EnvMarker) {
            throw "$EnvFile already exists and was not generated by TomeCMS. Move it aside, then run this script again."
        }
        foreach ($Line in Get-Content $EnvFile) {
            if ($Line -match '^TOME_CMS_INSTALL_TOKEN=(.*)$') { $InstallToken = $Matches[1] }
        }
    }
    if ($InstallToken.Length -lt 24) {
        $InstallToken = & node -e "process.stdout.write(require('node:crypto').randomBytes(24).toString('base64url'))"
    }

    $EnvLines = @(
        $EnvMarker,
        'TOME_CMS_SUPABASE_MODE=local',
        "PUBLIC_SUPABASE_URL=$ApiUrl",
        "PUBLIC_SUPABASE_PUBLISHABLE_KEY=$AnonKey",
        "SUPABASE_SECRET_KEY=$ServiceRoleKey",
        "TOME_CMS_INSTALL_TOKEN=$InstallToken",
        'TOME_CMS_DOMAIN='
    )
    [System.IO.File]::WriteAllLines($EnvFile, $EnvLines, [System.Text.UTF8Encoding]::new($false))

    if (-not (Test-Path 'node_modules/astro/package.json')) {
        & npm.cmd ci
        if ($LASTEXITCODE -ne 0) { throw 'npm dependency installation failed.' }
    }

    $env:PUBLIC_SUPABASE_URL = $ApiUrl
    $env:PUBLIC_SUPABASE_PUBLISHABLE_KEY = $AnonKey
    $env:SUPABASE_SECRET_KEY = $ServiceRoleKey
    $env:TOME_CMS_SUPABASE_MODE = 'local'
    $env:TOME_CMS_INSTALL_TOKEN = $InstallToken
    $env:TOME_CMS_DOMAIN = ''

    Write-Host ''
    Write-Host 'TomeCMS local services are ready.'
    Write-Host 'Installer: http://localhost:4321/install'
    Write-Host "Supabase Studio: $(if ($StudioUrl) { $StudioUrl } else { 'http://localhost:54323' })"
    Write-Host "Installation token: $InstallToken"
    Write-Host ''

    & npm.cmd run dev
    exit $LASTEXITCODE
}
finally {
    Pop-Location
}
