#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.local"
ENV_MARKER="# Generated by TomeCMS local setup"

fail() {
  echo "Error: $*" >&2
  exit 1
}

for command_name in node npm docker supabase awk; do
  command -v "$command_name" >/dev/null 2>&1 || fail "Missing '${command_name}'. Install it and run this script again."
done

[[ "$(uname -s)" == "Darwin" ]] || fail "Use scripts/dev-local-windows.ps1 on Windows."
docker info >/dev/null 2>&1 || fail "Docker Desktop is not running."

node_major="$(node -p "process.versions.node.split('.')[0]")"
(( node_major >= 20 )) || fail "Node.js 20 or newer is required."

cd "$ROOT_DIR"
[[ -f supabase/config.toml ]] || supabase init --yes
supabase start -x realtime,imgproxy,edge-runtime,logflare,vector,supavisor
supabase migration up --local

status_output="$(supabase status -o env)"
env_value() {
  printf '%s\n' "$status_output" | awk -F= -v key="$1" '$1 == key { value = substr($0, index($0, "=") + 1); gsub(/^"|"$/, "", value); print value }' | tail -n 1
}

api_url="$(env_value API_URL)"
anon_key="$(env_value ANON_KEY)"
service_role_key="$(env_value SERVICE_ROLE_KEY)"
studio_url="$(env_value STUDIO_URL)"
[[ -n "$api_url" && -n "$anon_key" && -n "$service_role_key" ]] || fail "Supabase did not return the required local credentials."

install_token=""
if [[ -f "$ENV_FILE" ]]; then
  [[ "$(head -n 1 "$ENV_FILE")" == "$ENV_MARKER" ]] || fail "${ENV_FILE} already exists and was not generated by TomeCMS. Move it aside, then run this script again."
  install_token="$(sed -n 's/^TOME_CMS_INSTALL_TOKEN=//p' "$ENV_FILE" | tail -n 1)"
fi
if (( ${#install_token} < 24 )); then
  install_token="$(node -e 'process.stdout.write(require("node:crypto").randomBytes(24).toString("base64url"))')"
fi

env_tmp="$(mktemp "${TMPDIR:-/tmp}/tomecms-env.XXXXXX")"
trap 'rm -f "$env_tmp"' EXIT
{
  echo "$ENV_MARKER"
  echo "PUBLIC_SUPABASE_URL=${api_url}"
  echo "PUBLIC_SUPABASE_ANON_KEY=${anon_key}"
  echo "SUPABASE_SERVICE_ROLE_KEY=${service_role_key}"
  echo "TOME_CMS_INSTALL_TOKEN=${install_token}"
  echo "TOME_CMS_DOMAIN="
} >"$env_tmp"
chmod 600 "$env_tmp"
mv "$env_tmp" "$ENV_FILE"

if [[ ! -f node_modules/astro/package.json ]]; then
  npm ci
fi

echo
echo "TomeCMS local services are ready."
echo "Installer: http://localhost:4321/install"
echo "Supabase Studio: ${studio_url:-http://localhost:54323}"
echo "Installation token: ${install_token}"
echo

export PUBLIC_SUPABASE_URL="$api_url"
export PUBLIC_SUPABASE_ANON_KEY="$anon_key"
export SUPABASE_SERVICE_ROLE_KEY="$service_role_key"
export TOME_CMS_INSTALL_TOKEN="$install_token"
export TOME_CMS_DOMAIN=""
exec npm run dev
