#!/usr/bin/env node
/**
 * Copies the IBM Plex Sans Thai faces this CMS uses into public/ as static assets.
 *
 * The fonts are served from the site itself rather than fetched from Google, which
 * removes two connections and a render-blocking stylesheet from the critical path.
 * They are static rather than bundled on purpose: Astro splits CSS per route, and
 * a page that does not happen to receive the bundle carrying @font-face would lose
 * the typeface entirely.
 *
 * Only latin and thai are kept — this CMS writes in exactly those two scripts —
 * and the unicode-range comes from the package's own combined stylesheet, so the
 * browser downloads a subset only when a page actually contains those characters.
 * Fontsource's per-subset stylesheets omit unicode-range, so they cannot be used
 * directly: without it the latin and thai faces shadow one another.
 *
 * Usage: node scripts/sync-fonts.mjs [--check]
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGE = join(ROOT, 'node_modules/@fontsource/ibm-plex-sans-thai');
const OUT_DIR = join(ROOT, 'public/fonts');
const OUT_CSS = join(ROOT, 'public/fonts.css');
const WEIGHTS = [400, 500, 600, 700];
const SUBSETS = ['latin', 'thai'];

/** Pulls the @font-face blocks for the wanted subsets out of a combined stylesheet. */
export function selectFaces(css, weight, subsets) {
  const faces = [];
  for (const subset of subsets) {
    const marker = `/* ibm-plex-sans-thai-${subset}-${weight}-normal */`;
    const start = css.indexOf(marker);
    if (start === -1) throw new Error(`Missing ${subset} ${weight} in the package stylesheet.`);
    const block = css.slice(start, css.indexOf('}', start) + 1);
    const range = /unicode-range: ([^;]+);/.exec(block);
    if (!range) throw new Error(`${subset} ${weight} has no unicode-range; the subsets would shadow each other.`);
    faces.push({ file: `ibm-plex-sans-thai-${subset}-${weight}-normal.woff2`, subset, unicodeRange: range[1], weight });
  }
  return faces;
}

export function renderCss(faces) {
  return [
    '/* Generated by scripts/sync-fonts.mjs — do not edit by hand. */',
    ...faces.map(({ file, subset, unicodeRange, weight }) => [
      `/* ${subset} ${weight} */`,
      '@font-face {',
      "  font-family: 'IBM Plex Sans Thai';",
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2');`,
      `  unicode-range: ${unicodeRange};`,
      '}',
    ].join('\n')),
  ].join('\n\n') + '\n';
}

if (process.argv.includes('--self-test')) {
  const sample = [
    '/* ibm-plex-sans-thai-thai-400-normal */',
    '@font-face {', "  font-family: 'IBM Plex Sans Thai';", '  unicode-range: U+0E01-0E5B;', '}',
  ].join('\n');
  const [face] = selectFaces(sample, 400, ['thai']);
  assert(face.unicodeRange === 'U+0E01-0E5B', 'the unicode-range must survive extraction');
  assert(renderCss([face]).includes("url('/fonts/ibm-plex-sans-thai-thai-400-normal.woff2')"), 'the url must point at the public copy');

  let threw = false;
  try { selectFaces(sample.replace('  unicode-range: U+0E01-0E5B;\n', ''), 400, ['thai']); } catch { threw = true; }
  assert(threw, 'a face with no unicode-range must fail loudly, not ship a shadowing face');

  threw = false;
  try { selectFaces(sample, 700, ['thai']); } catch { threw = true; }
  assert(threw, 'a missing weight must fail rather than silently drop');
  console.log('sync-fonts self-test passed.');
} else {
  const faces = WEIGHTS.flatMap((weight) =>
    selectFaces(readFileSync(join(PACKAGE, `${weight}.css`), 'utf8'), weight, SUBSETS));

  rmSync(OUT_DIR, { force: true, recursive: true });
  mkdirSync(OUT_DIR, { recursive: true });
  for (const { file } of faces) {
    writeFileSync(join(OUT_DIR, file), readFileSync(join(PACKAGE, 'files', file)));
  }
  writeFileSync(OUT_CSS, renderCss(faces));

  const copied = readdirSync(OUT_DIR).length;
  if (copied !== faces.length) throw new Error(`Expected ${faces.length} font files, wrote ${copied}.`);
  console.log(`Synced ${copied} font files and public/fonts.css.`);
}

function assert(condition, message) {
  if (!condition) throw new Error(`Self-test failed: ${message}`);
}
