#!/usr/bin/env node
/**
 * Copies the faces this CMS uses into public/ as static assets.
 *
 * The fonts are served from the site itself rather than fetched from Google, which
 * removes two connections and a render-blocking stylesheet from the critical path.
 * They are static rather than bundled on purpose: Astro splits CSS per route, and
 * a page that does not happen to receive the bundle carrying @font-face would lose
 * the typeface entirely.
 *
 * Only latin and thai are kept — this CMS writes in exactly those two scripts —
 * and the unicode-range comes from the package's own combined stylesheet, so the
 * browser downloads a subset only when a page actually contains those characters.
 * Fontsource's per-subset stylesheets omit unicode-range, so they cannot be used
 * directly: without it the latin and thai faces shadow one another.
 *
 * Two families, because the admin is a tool and an article is not: Google Sans
 * carries the display roles -- the post title the writer types and the reader gets,
 * the hero, the card and section headings -- and IBM Plex Sans Thai carries the
 * interface and the body. Only the weights each family is actually used at are
 * copied, which is why display ships two and the interface ships four.
 *
 * A theme's own face is written into that theme's directory instead of fonts.css, and
 * its stylesheet imports it: fonts.css is linked by every page, and a reader of one
 * theme should not be handed the faces of another. Trirong, Almanac's headings, is the
 * one there is.
 *
 * --check writes nothing and fails when what is on disk is not what a sync would write,
 * so a stylesheet edited by hand or a package bumped without a sync is caught.
 *
 * Usage: node scripts/sync-fonts.mjs [--check]
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public/fonts');
const SHARED_CSS = 'public/fonts.css';
const SUBSETS = ['latin', 'thai'];
const FAMILIES = [
  // --font-display: 400 on the section and notice headings, 700 everywhere else.
  { id: 'google-sans', family: 'Google Sans', weights: [400, 700], css: SHARED_CSS },
  // --font-body: the interface runs the full range.
  { id: 'ibm-plex-sans-thai', family: 'IBM Plex Sans Thai', weights: [400, 500, 600, 700], css: SHARED_CSS },
  // Almanac's --font-display: 400 for the large headings, 600 for the card titles.
  { id: 'trirong', family: 'Trirong', weights: [400, 600], css: 'src/themes/almanac/fonts.css' },
];

/** Pulls the @font-face blocks for the wanted subsets out of a combined stylesheet. */
export function selectFaces(css, weight, subsets, { id = 'ibm-plex-sans-thai', family = 'IBM Plex Sans Thai' } = {}) {
  const faces = [];
  for (const subset of subsets) {
    const marker = `/* ${id}-${subset}-${weight}-normal */`;
    const start = css.indexOf(marker);
    if (start === -1) throw new Error(`Missing ${subset} ${weight} in the ${family} package stylesheet.`);
    const block = css.slice(start, css.indexOf('}', start) + 1);
    const range = /unicode-range: ([^;]+);/.exec(block);
    if (!range) throw new Error(`${family} ${subset} ${weight} has no unicode-range; the subsets would shadow each other.`);
    faces.push({ family, file: `${id}-${subset}-${weight}-normal.woff2`, id, subset, unicodeRange: range[1], weight });
  }
  return faces;
}

export function renderCss(faces) {
  return [
    '/* Generated by scripts/sync-fonts.mjs — do not edit by hand. */',
    ...faces.map(({ family, file, subset, unicodeRange, weight }) => [
      `/* ${family} ${subset} ${weight} */`,
      '@font-face {',
      `  font-family: '${family}';`,
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2');`,
      `  unicode-range: ${unicodeRange};`,
      '}',
    ].join('\n')),
  ].join('\n\n') + '\n';
}

if (process.argv.includes('--self-test')) {
  const sample = [
    '/* ibm-plex-sans-thai-thai-400-normal */',
    '@font-face {', "  font-family: 'IBM Plex Sans Thai';", '  unicode-range: U+0E01-0E5B;', '}',
  ].join('\n');
  const [face] = selectFaces(sample, 400, ['thai']);
  assert(face.unicodeRange === 'U+0E01-0E5B', 'the unicode-range must survive extraction');
  assert(renderCss([face]).includes("url('/fonts/ibm-plex-sans-thai-thai-400-normal.woff2')"), 'the url must point at the public copy');

  let threw = false;
  try { selectFaces(sample.replace('  unicode-range: U+0E01-0E5B;\n', ''), 400, ['thai']); } catch { threw = true; }
  assert(threw, 'a face with no unicode-range must fail loudly, not ship a shadowing face');

  threw = false;
  try { selectFaces(sample, 700, ['thai']); } catch { threw = true; }
  assert(threw, 'a missing weight must fail rather than silently drop');
  console.log('sync-fonts self-test passed.');
} else {
  const faces = FAMILIES.flatMap(({ css, id, family, weights }) => {
    const pkg = join(ROOT, 'node_modules/@fontsource', id);
    return weights.flatMap((weight) =>
      selectFaces(readFileSync(join(pkg, `${weight}.css`), 'utf8'), weight, SUBSETS, { family, id })
        .map((face) => ({ ...face, css, pkg })));
  });
  const stylesheets = [...new Set(faces.map(({ css }) => css))]
    .map((css) => ({ css, text: renderCss(faces.filter((face) => face.css === css)) }));

  if (process.argv.includes('--check')) {
    const drift = [
      ...stylesheets.filter(({ css, text }) => !existsSync(join(ROOT, css)) || readFileSync(join(ROOT, css), 'utf8') !== text)
        .map(({ css }) => css),
      ...faces.filter(({ file, pkg }) => !existsSync(join(OUT_DIR, file))
        || !readFileSync(join(OUT_DIR, file)).equals(readFileSync(join(pkg, 'files', file))))
        .map(({ file }) => `public/fonts/${file}`),
      ...(existsSync(OUT_DIR) ? readdirSync(OUT_DIR) : [])
        .filter((file) => !faces.some((face) => face.file === file))
        .map((file) => `public/fonts/${file} (not synced)`),
    ];
    if (drift.length) {
      console.error(`The fonts are not what a sync would write:\n${drift.map((path) => `  - ${path}`).join('\n')}\nRun npm run fonts:sync.`);
      process.exit(1);
    }
    console.log(`The ${faces.length} font files and ${stylesheets.length} stylesheets match a sync.`);
  } else {
    rmSync(OUT_DIR, { force: true, recursive: true });
    mkdirSync(OUT_DIR, { recursive: true });
    for (const { file, pkg } of faces) {
      writeFileSync(join(OUT_DIR, file), readFileSync(join(pkg, 'files', file)));
    }
    for (const { css, text } of stylesheets) writeFileSync(join(ROOT, css), text);

    const copied = readdirSync(OUT_DIR).length;
    if (copied !== faces.length) throw new Error(`Expected ${faces.length} font files, wrote ${copied}.`);
    console.log(`Synced ${copied} font files and ${stylesheets.map(({ css }) => css).join(', ')}.`);
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(`Self-test failed: ${message}`);
}
